// -------------------------------------------------------------
// 
// File Name: hdlsrc\LLE\PushPopCounter.v
// Created: 2020-07-09 10:41:45
// 
// Generated by MATLAB 9.8 and HDL Coder 3.16
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: PushPopCounter
// Source Path: LLE/LLEHDL/IterativeFilter/Image Filter4/LineBuffer/DATA_MEMORY/PushPopCounter
// Hierarchy Level: 5
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module PushPopCounter
          (clk,
           reset,
           enb,
           hStartIn,
           popIn,
           popEnable,
           hEndIn,
           writeCountPrev,
           wrAddr,
           pushOut,
           rdAddr,
           popOut,
           EndofLine);


  input   clk;
  input   reset;
  input   enb;
  input   hStartIn;
  input   popIn;
  input   popEnable;
  input   hEndIn;
  input   [10:0] writeCountPrev;  // ufix11
  output  [10:0] wrAddr;  // ufix11
  output  pushOut;
  output  [10:0] rdAddr;  // ufix11
  output  popOut;
  output  EndofLine;


  reg [10:0] writePrevREG;  // ufix11
  wire InBetweenEn;
  wire ConstantZero;
  wire InBetweenRegIn;
  reg  InBetween;
  reg [10:0] writeCount;  // ufix11
  wire relop_relop1;
  wire writeContinue;
  wire writeEN;
  reg  writeStoreEn;
  reg [10:0] writeCountNext;  // ufix11
  reg [10:0] writeCountCurrent;  // ufix11
  wire [10:0] readCountCompare;  // ufix11
  wire readCountCompare_is_not0;
  wire popTerm2;
  reg [10:0] readCount;  // ufix11
  wire relop_relop1_1;
  wire and_bool;
  wire readCountCompare_is_not0_1;
  wire popTerm1;
  wire popCounter;
  wire [10:0] constantTwo;  // ufix11
  wire [10:0] readCountAhead;  // ufix11
  wire relop_relop1_2;


  always @(posedge clk or posedge reset)
    begin : reg_rsvd_process
      if (reset == 1'b1) begin
        writePrevREG <= 11'b00000000000;
      end
      else begin
        if (enb && hStartIn) begin
          writePrevREG <= writeCountPrev;
        end
      end
    end



  assign InBetweenEn = hStartIn | hEndIn;



  assign ConstantZero = 1'b0;



  assign InBetweenRegIn = (hStartIn == 1'b0 ? hEndIn :
              ConstantZero);



  always @(posedge clk or posedge reset)
    begin : reg_rsvd_1_process
      if (reset == 1'b1) begin
        InBetween <= 1'b0;
      end
      else begin
        if (enb && InBetweenEn) begin
          InBetween <= InBetweenRegIn;
        end
      end
    end



  assign relop_relop1 = writeCount <= writePrevREG;



  assign writeContinue = relop_relop1 & InBetween;



  assign writeEN = writeContinue | popIn;



  // Free running, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  always @(posedge clk or posedge reset)
    begin : Write_Count_process
      if (reset == 1'b1) begin
        writeCount <= 11'b00000000000;
      end
      else begin
        if (enb) begin
          if (hStartIn == 1'b1) begin
            writeCount <= 11'b00000000000;
          end
          else if (writeEN == 1'b1) begin
            writeCount <= writeCount + 11'b00000000001;
          end
        end
      end
    end



  assign wrAddr = writeCount;

  assign pushOut = writeEN;

  always @(posedge clk or posedge reset)
    begin : reg_rsvd_2_process
      if (reset == 1'b1) begin
        writeStoreEn <= 1'b0;
      end
      else begin
        if (enb) begin
          writeStoreEn <= hEndIn;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : reg_rsvd_3_process
      if (reset == 1'b1) begin
        writeCountNext <= 11'b00000000000;
      end
      else begin
        if (enb && writeStoreEn) begin
          writeCountNext <= writeCount;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : reg_rsvd_4_process
      if (reset == 1'b1) begin
        writeCountCurrent <= 11'b00000000000;
      end
      else begin
        if (enb && hStartIn) begin
          writeCountCurrent <= writeCountNext;
        end
      end
    end



  assign readCountCompare_is_not0 = readCountCompare != 11'b00000000000;



  assign popTerm2 = readCountCompare_is_not0 & InBetween;



  assign relop_relop1_1 = readCount <= writeCountCurrent;



  assign and_bool = popEnable & relop_relop1_1;



  assign readCountCompare = {10'b0, and_bool};



  assign readCountCompare_is_not0_1 = readCountCompare != 11'b00000000000;



  assign popTerm1 = popIn & readCountCompare_is_not0_1;



  assign popCounter = popTerm1 | popTerm2;



  // Free running, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  always @(posedge clk or posedge reset)
    begin : Read_Count_process
      if (reset == 1'b1) begin
        readCount <= 11'b00000000000;
      end
      else begin
        if (enb) begin
          if (hStartIn == 1'b1) begin
            readCount <= 11'b00000000000;
          end
          else if (popCounter == 1'b1) begin
            readCount <= readCount + 11'b00000000001;
          end
        end
      end
    end



  assign rdAddr = readCount;

  assign popOut = popCounter;

  assign constantTwo = 11'b00000000100;



  assign readCountAhead = readCount + constantTwo;



  assign relop_relop1_2 = readCountAhead == writeCountCurrent;



  assign EndofLine = relop_relop1_2;

endmodule  // PushPopCounter

