// -------------------------------------------------------------
// 
// File Name: hdlsrc\LLE\Vertical_Padder_block.v
// Created: 2020-07-09 10:41:45
// 
// Generated by MATLAB 9.8 and HDL Coder 3.16
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Vertical_Padder_block
// Source Path: LLE/LLEHDL/IterativeFilter/Image Filter3/LineBuffer/Vertical Padder
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Vertical_Padder_block
          (dataVectorIn_0,
           dataVectorIn_1,
           dataVectorIn_2,
           verPadCount,
           dataVectorOut_0,
           dataVectorOut_1,
           dataVectorOut_2);


  input   [19:0] dataVectorIn_0;  // ufix20_En12
  input   [19:0] dataVectorIn_1;  // ufix20_En12
  input   [19:0] dataVectorIn_2;  // ufix20_En12
  input   [10:0] verPadCount;  // ufix11
  output  [19:0] dataVectorOut_0;  // ufix20_En12
  output  [19:0] dataVectorOut_1;  // ufix20_En12
  output  [19:0] dataVectorOut_2;  // ufix20_En12


  wire verSEL1;
  wire [19:0] DataLineOut1;  // ufix20_En12
  wire verSEL3;
  wire [19:0] DataLineOut3;  // ufix20_En12


  assign verSEL1 = verPadCount > 11'b00000000001;



  assign DataLineOut1 = (verSEL1 == 1'b0 ? dataVectorIn_0 :
              dataVectorIn_1);



  assign dataVectorOut_0 = DataLineOut1;

  assign dataVectorOut_1 = dataVectorIn_1;

  assign verSEL3 = verPadCount < 11'b00000000001;



  assign DataLineOut3 = (verSEL3 == 1'b0 ? dataVectorIn_2 :
              dataVectorIn_1);



  assign dataVectorOut_2 = DataLineOut3;

endmodule  // Vertical_Padder_block

