// -------------------------------------------------------------
// 
// File Name: hdlsrc\LLE\Vertical_Padder.v
// Created: 2020-07-09 10:41:45
// 
// Generated by MATLAB 9.8 and HDL Coder 3.16
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Vertical_Padder
// Source Path: LLE/LLEHDL/IterativeFilter/Image Filter4/LineBuffer/Vertical Padder
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Vertical_Padder
          (dataVectorIn_0,
           dataVectorIn_1,
           dataVectorIn_2,
           verPadCount,
           dataVectorOut_0,
           dataVectorOut_1,
           dataVectorOut_2);


  input   [23:0] dataVectorIn_0;  // ufix24_En16
  input   [23:0] dataVectorIn_1;  // ufix24_En16
  input   [23:0] dataVectorIn_2;  // ufix24_En16
  input   [10:0] verPadCount;  // ufix11
  output  [23:0] dataVectorOut_0;  // ufix24_En16
  output  [23:0] dataVectorOut_1;  // ufix24_En16
  output  [23:0] dataVectorOut_2;  // ufix24_En16


  wire verSEL1;
  wire [23:0] DataLineOut1;  // ufix24_En16
  wire verSEL3;
  wire [23:0] DataLineOut3;  // ufix24_En16


  assign verSEL1 = verPadCount > 11'b00000000001;



  assign DataLineOut1 = (verSEL1 == 1'b0 ? dataVectorIn_0 :
              dataVectorIn_1);



  assign dataVectorOut_0 = DataLineOut1;

  assign dataVectorOut_1 = dataVectorIn_1;

  assign verSEL3 = verPadCount < 11'b00000000001;



  assign DataLineOut3 = (verSEL3 == 1'b0 ? dataVectorIn_2 :
              dataVectorIn_1);



  assign dataVectorOut_2 = DataLineOut3;

endmodule  // Vertical_Padder

